---
- hosts: all
  become: true
  roles:
    - role: base
    - role: ubuntu
    - role: centos

  tasks:
    - name: Copy default site html to apache location
      tags: httpd,centos
      copy:
        src: default_site.html
        dest: /var/www/html/index.html
        owner: apache
        group: apache
        mode: 0644
      when: ansible_distribution == "CentOS"
    - name: change email address of httpd in centos
      tags: httpd,centos
      lineinfile:
        path: /etc/httpd/conf/httpd.conf
        regexp: '^ServerAdmin'
        line: ServerAdmin amin@gmail.com
      when: ansible_distribution == "CentOS"
      register: httpd
    - name: service httpd restarted if line changed
      tags: httpd,centos
      service:
        name: httpd
        state: restarted
      when: httpd.changed

